### ISSUE TITLE
Install steps do not seem to work

### ISSUE THREAD

**Issue by jeffbaumes** [julians/probing-projections#2]
A few install steps that seem to be missed in the documentation:
1. I needed to do a `bower install` in the web directory.
2. I needed to install compass, which is a bit tricky in latest macOS (see https://github.com/Compass/compass/issues/2018)
3. When I then do grunt watch, I get this error on the webpage console: "Uncaught ReferenceError: d3 is not defined"

**Comment by julians** [comment]
Thanks for reporting this! Fixed in https://github.com/julians/probing-projections/commit/6450868e349e56c4d33d1abc9b662d777af6329e
